### PR TITLE
Add new exciting content

### PR DESCRIPTION
**Pull request by MJWindsor**
I've added new content that I think makes the readme a lot more exciting and user friendly.

### CODE REVIEW

**Review by MJWindsorQUT — CHANGES_REQUESTED** [review]
This content is exciting but it could be better. Please make the content even more exciting.

**Comment by MJWindsor** [comment]
I've made this content super exciting now

**Review by MJWindsorQUT — CHANGES_REQUESTED** [review]
That's great. Please squash to a single commit then I'll accept the pull-request

**Review by MJWindsorQUT — APPROVED** [review]
Great, thanks!

**Pull request merged**
